# environment.yml
name: cse-151-ml-env  # Choose a descriptive name for your environment

channels:
  - pytorch       # Recommended channel for PyTorch
  - conda-forge   # A good source for many packages
  - defaults      # Default conda channel

dependencies:
  # --- Core Python and Conda Packages ---
  - python=3.10     # Or specify your desired Python version (e.g., 3.9, 3.11)
  - pip             # Include pip to install packages below
  - numpy           # From 'import numpy'
  - pytorch         # From 'import torch' - Installing via conda is recommended
  - torchvision     # Often used with PyTorch (good practice to include)
  - torchaudio      # Often used with PyTorch (good practice to include)
  - xarray          # From pip install command and import
  - zarr            # From pip install command
  - dask            # From pip install command and import
  - matplotlib      # From pip install command and import
  - cftime          # From pip install command

  # --- Pip Packages ---
  # Packages listed here will be installed using pip *after* conda packages
  - pip:
    - lightning       # From pip install command and import (often listed as pytorch-lightning too)
    - wandb           # From pip install command
    - einops          # From pip install command