# @package _global_

defaults:
  - data: default
  - model: enhanced_climate_unet
  # - model: simple_cnn
  - training: default
  - trainer: default
  - _self_

# Global configs
seed: 42

# Wandb logging, all arguments are only used if use_wandb is set to true
use_wandb: true
wandb_project: "Deep-sea-kucumber-cse-151b-competition"
wandb_entity: "guoxuan-xu8-uc-san-diego"
run_name: "demo_enhanced_climate_unnet"

# Path to a checkpoint to load. If set, will load this checkpoint and resume training (evaluation)
ckpt_path: null

hydra:
  job:
    chdir: true
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
